### PR TITLE
Merge jdk:master

### PR DESCRIPTION
**Pull request by AntonKozlov**
Hi, please review a merge of openjdk/jdk:master into jdk-macos branch. Once reviewed, I'm going to propose the result of this merge as JEP-391 implementation to jdk:master. 

There is non-trivial changes in gtest to avoid fighting with W^X asserts. Now gtests are started in Write mode, as if they are running in the VM context.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Reviewers
 * [Bernhard Urban-Forster](https://openjdk.java.net/census#burban) (@lewurm - Author)

### Download
`$ git fetch https://git.openjdk.java.net/aarch64-port pull/12/head:pull/12`
`$ git checkout pull/12`

### CODE REVIEW

**Comment by AntonKozlov** [comment]
@lewurm @luhenry, could you check windows/aarch64 is still fine?

**Comment by lewurm** [comment]
Windows+AArch64
================

Configure:
```
A new configuration has been successfully created in
/cygdrive/c/work/aarch64-port/build/windows-aarch64-server-release
using configure arguments '--openjdk-target=aarch64-unknown-cygwin --with-jvm-features=-zgc,-jfr,-aot --with-boot-jdk=/cygdrive/c/work/jdk_x64_windows/jdk-17+5'.

Configuration summary:
* Name:           windows-aarch64-server-release
* Debug level:    release
* HS debug level: product
* JVM variants:   server
* JVM features:   server: 'cds compiler1 compiler2 epsilongc g1gc graal jni-check jvmci jvmti management nmt parallelgc serialgc services shenandoahgc vm-structs'
* OpenJDK target: OS: windows, CPU architecture: aarch64, address length: 64
* Version string: 17-internal+0-adhoc.NORTHAMERICAbeurba.aarch64-port (17-internal)

Tools summary:
* Environment:    cygwin version 3.1.7(0.340/5/3), 2020-08-22 17:48; windows version 10.0.19042.746; prefix "/cygdrive"; root "C:\cygwin64"
* Boot JDK:       openjdk version "17" 2021-09-14 OpenJDK Runtime Environment AdoptOpenJDK (build 17+5-202101200336) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 17+5-202101200336, mixed mode, sharing) (at /cygdrive/c/work/jdk_x6~1/jdk-17~1)
* Toolchain:      microsoft (Microsoft Visual Studio 2019)
* C Compiler:     Version 19.28.29334 (at /cygdrive/c/progra~2/micros~3/2019/enterp~1/vc/tools/msvc/1428~1.293/bin/hostx64/arm64/cl.exe)
* C++ Compiler:   Version 19.28.29334 (at /cygdrive/c/progra~2/micros~3/2019/enterp~1/vc/tools/msvc/1428~1.293/bin/hostx64/arm64/cl.exe)

Build performance summary:
* Cores to use:   8
* Memory limit:   10369 MB
```
Test: `hotspot/jtreg:tier1`, no regression compared to master:
```
Test results: passed 1.503; failed: 122; error: 9
```
List of failures and errors: https://gist.github.com/lewurm/04a1d46c27ab1fcb89f27ce4b0eb66c2
Some of those failures are due to the way I'm running `jtreg`, that is not via `make test [...]` as I'm cross-compiling, but running it manually, and I know for example I'm missing some paths to make JVMCI tests happy. But some are suspicious:  I recently discovered an oddity around floating points and varags in the Windows ABI (floats are pushed in integer regs), which I believe we don't respect in HotSpot. I should take some time to look into that... anyway, not related to this PR 🙂 

Linux+AArch64
============

Configure:
```
/home/beurba/work/aarch64-port/build/linux-aarch64-server-fastdebug
using configure arguments '--with-boot-jdk=/home/beurba/work/jdk-16+13 --with-debug-level=fastdebug --with-jtreg'.

Configuration summary:
* Name:           linux-aarch64-server-fastdebug
* Debug level:    fastdebug
* HS debug level: fastdebug
* JVM variants:   server
* JVM features:   server: 'aot cds compiler1 compiler2 epsilongc g1gc graal jfr jni-check jvmci jvmti management nmt parallelgc serialgc services shenandoahgc vm-structs zgc'
* OpenJDK target: OS: linux, CPU architecture: aarch64, address length: 64
* Version string: 17-internal+0-adhoc.beurba.aarch64-port (17-internal)

Tools summary:
* Boot JDK:       openjdk version "16" 2021-03-16 OpenJDK Runtime Environment AdoptOpenJDK (build 16+13-202008281038) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 16+13-202008281038, mixed mode, sharing) (at /home/beurba/work/jdk-16+13)
* Toolchain:      gcc (GNU Compiler Collection)
* C Compiler:     Version 9.2.1 (at /usr/bin/gcc)
* C++ Compiler:   Version 9.2.1 (at /usr/bin/g++)

Build performance summary:
* Cores to use:   256
* Memory limit:   514866 MB
```

Test: `hotspot/jtreg:tier1` (did not compare with master)
```
Test results: passed: 1,764; failed: 10
```
List of failures: https://gist.github.com/lewurm/bc0959194e2f476747df99ba85c9119f

macOS+AArch64
=============
Configure:
```
/Users/lewurm/work/aarch64-port/build/macosx-aarch64-server-release
using configure arguments '--build=aarch64-apple-darwin --host=aarch64-apple-darwin --with-boot-jdk=/Users/lewurm/work/jdk-17+5/Contents/Home --with-build-jdk=/Users/lewurm/work/jdk-17+5/Contents/Home --with-jtreg --with-gtest=/Users/lewurm/work/googletest-release-1.8.1'.

Configuration summary:
* Name:           macosx-aarch64-server-release
* Debug level:    release
* HS debug level: product
* JVM variants:   server
* JVM features:   server: 'compiler1 compiler2 dtrace epsilongc g1gc graal jfr jni-check jvmci jvmti management nmt parallelgc serialgc services shenandoahgc vm-structs'
* OpenJDK target: OS: macosx, CPU architecture: aarch64, address length: 64
* Version string: 17-internal+0-adhoc.lewurm.aarch64-port (17-internal)

Tools summary:
* Boot JDK:       src Unable to map CDS archive -- os::vm_allocation_granularity() expected: 4096 actual: 16384 openjdk version "17" 2021-09-14 OpenJDK Runtime Environment AdoptOpenJDK (build 17+5-202101200336) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 17+5-202101200336, mixed mode) (at /Users/lewurm/work/jdk-17+5/Contents/Home)
* Toolchain:      clang (clang/LLVM from Xcode 12.2)
* C Compiler:     Version 12.0.0 (at /usr/bin/clang)
* C++ Compiler:   Version 12.0.0 (at /usr/bin/clang++)

Build performance summary:
* Cores to use:   8
* Memory limit:   16384 MB
```

Test: `hotspot/jtreg:tier1` (did not compare with master... obviously 😄 )
```
Test results: passed: 1,589; failed: 3
```
List of failures: https://gist.github.com/lewurm/859ff38a6c635233f3006f520262f840

**Review by lewurm — APPROVED** [review]
Thank you Anton, looks good to me 🙂

**Comment by lewurm** [comment]
Note for potential other reviewers, better view for looking at the changes: https://github.com/openjdk/aarch64-port/compare/master...AntonKozlov:jdk-macos

**Comment by AntonKozlov** [comment]
Thanks for checking! Good point, I haven't looked at the test results closely for some time.

Gtest failures are probably caused by the missing `--with-gtest` configure parameter. I've checked them, they are passing before and after merge on linux/aarch64

runtime/CompressedOops/CompressedClassPointers.java has a lot of guards for various systems, it seems we miss one for macos/aarch64

compiler/jvmci/jdk.vm.ci.code.test/src/jdk/vm/ci/code/test/NativeCallTest.java is interesting, especially since we don't support JVMCI :) It looks like a test bug, it should not run on mac

I will make a PR with the JEP implementation and will look at these tests while the review is going.

**Comment by lewurm** [comment]
> Gtest failures are probably caused by the missing `--with-gtest` configure parameter. I've checked them, they are passing before and after merge on linux/aarch64

Indeed! I missed `--with-gtest` on Linux.

> compiler/jvmci/jdk.vm.ci.code.test/src/jdk/vm/ci/code/test/NativeCallTest.java is interesting, especially since we don't support JVMCI :) It looks like a test bug, it should not run on mac

It does work in principle though:
```
$ ./build/macosx-aarch64-server-release/images/jdk/bin/java -XX:+UnlockExperimentalVMOptions -XX:+UseJVMCICompiler -XX:+BootstrapJVMCI -version
Bootstrapping JVMCI............................... in 8410 ms (compiled 3128 methods)
openjdk version "17-internal" 2021-09-14
OpenJDK Runtime Environment (build 17-internal+0-adhoc.lewurm.aarch64-port)
OpenJDK 64-Bit Server VM (build 17-internal+0-adhoc.lewurm.aarch64-port, mixed mode)
```

I kind of sneaked in macOS support in my PR for Windows+AArch64: https://github.com/openjdk/jdk/pull/685

**Comment by AntonKozlov** [comment]
> [ JVMCI ] does work in principle though:

Hmm, that was unexpected :) Based on the test, JVMCI calling convention is broken. I'll check how much efforts would it require to fix the test

**Pull request merged**
