### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by AntonKozlov**
This PR is a part of #5 and it merges recent changes from openjdk/jdk master. Few fixes are made to make the merge buildable and functional

* d81cca31ab7, 0ab1e1ccb7d -- revert "Import JDK-8234930 v2: Use MAP_JIT when allocating pages for code cache on macOS" to make a complete commit after (b41b3a949e3)
f7c60d7c098 Merge remote-tracking branch 'upstream/master' into macos-aarch64-public -- have no conflicts
051357ef977 Fix merge -- replicates changes in os_bsd_aarch64 and fixes build
33c47611da3 Add missing include StubRoutines inline -- a missing part of f888accb52c
b41b3a949e3 Import JDK-8234930 v3: Use MAP_JIT when allocating pages for code cache on macOS -- a complete change to introduce MAP_JIT, may change in future

It's also tests merge-style PR (https://github.com/openjdk/aarch64-port/pull/5#issuecomment-726893549). Let's see how it will be processed by SKARA tooling. Vanilla Github merge ability made commit with my personal email 499487333abcb0700e8d1403df778ddb65cc9886, probably something we would not like to have :)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Error
&nbsp;⚠️ Could not determine the source for this merge. A Merge PR title must be specified on the format: Merge `project`:`branch` to allow verification of the merge contents.

### Testing

|     | Linux x64 | Linux x86 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- | ----- |
| Build | ❌ (1/5 failed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) | ✔️ (2/2 passed) |
| Test (tier1) |    |  ❌ (5/9 failed) | ❌ (5/9 failed) | ❌ (6/9 failed) |

**Failed test tasks**
- [Linux x64 (build hotspot zero)](https://github.com/AntonKozlov/aarch64-port/runs/1408303172)
- [Linux x86 (hs/tier1 common)](https://github.com/AntonKozlov/aarch64-port/runs/1408475383)
- [Linux x86 (hs/tier1 compiler)](https://github.com/AntonKozlov/aarch64-port/runs/1408475407)
- [Linux x86 (hs/tier1 gc)](https://github.com/AntonKozlov/aarch64-port/runs/1408475466)
- [Linux x86 (hs/tier1 runtime)](https://github.com/AntonKozlov/aarch64-port/runs/1408475496)
- [Linux x86 (hs/tier1 serviceability)](https://github.com/AntonKozlov/aarch64-port/runs/1408475523)
- [Windows x64 (hs/tier1 common)](https://github.com/AntonKozlov/aarch64-port/runs/1408587538)
- [Windows x64 (hs/tier1 compiler)](https://github.com/AntonKozlov/aarch64-port/runs/1408587559)
- [Windows x64 (hs/tier1 gc)](https://github.com/AntonKozlov/aarch64-port/runs/1408587586)
- [Windows x64 (hs/tier1 runtime)](https://github.com/AntonKozlov/aarch64-port/runs/1408587609)
- [Windows x64 (hs/tier1 serviceability)](https://github.com/AntonKozlov/aarch64-port/runs/1408587631)
- [macOS x64 (hs/tier1 common)](https://github.com/AntonKozlov/aarch64-port/runs/1408487902)
- [macOS x64 (hs/tier1 compiler)](https://github.com/AntonKozlov/aarch64-port/runs/1408487928)
- [macOS x64 (hs/tier1 gc)](https://github.com/AntonKozlov/aarch64-port/runs/1408487942)
- [macOS x64 (hs/tier1 runtime)](https://github.com/AntonKozlov/aarch64-port/runs/1408487954)
- [macOS x64 (hs/tier1 serviceability)](https://github.com/AntonKozlov/aarch64-port/runs/1408487979)
- [macOS x64 (jdk/tier1 part 1)](https://github.com/AntonKozlov/aarch64-port/runs/1408487836)

### Reviewers
 * [Bernhard Urban-Forster](https://openjdk.java.net/census#burban) (@lewurm - Author)
 * [Ludovic Henry](https://openjdk.java.net/census#luhenry) (@luhenry - Author)

### Download
`$ git fetch https://git.openjdk.java.net/aarch64-port pull/6/head:pull/6`
`$ git checkout pull/6`

### CODE REVIEW

**Review by lewurm — APPROVED** [review]

**Comment by lewurm** [comment]
```
Error

⚠️ Merge commit message is not Merge, but: Merge jdk:master
```
hmm 😉

**Review by luhenry — APPROVED** [review]

**Comment by lewurm** [comment]
I think Anton wanted to try the SKARA tooling 😕 

> Let's see how it will be processed by SKARA tooling. Vanilla Github merge ability made commit with my personal email 4994873, probably something we would not like to have :)

**Comment by AntonKozlov** [comment]
That's OK, I think we'll have an another chance

**Pull request merged**
