### PR TITLE
8253795: Implementation of JEP 391: macOS/AArch64 Port

### PR DESCRIPTION
**Pull request by VladimirKempik**
Backport of JEP-391 to jdk11u-dev
The PR has two commits, one is simple copy of linux_aarch64 to bsd_aarch64. This will allow to see the difference applied to os_cpu against linux_aarch64 version.

Total issues:
JDK-8253795: Implementation of JEP 391: macOS/AArch64 Port
JDK-8253816: Support macOS W^X
JDK-8253817: Support macOS Aarch64 ABI in Interpreter
JDK-8253818: Support macOS Aarch64 ABI for compiled wrappers
JDK-8253819: Implement os/cpu for macOS/AArch64
JDK-8253839: Update tests and JDK code for macOS/Aarch64
JDK-8254941: Implement Serviceability Agent for macOS/AArch64
JDK-8255776: Change build system for macOS/AArch64
JDK-8262903: [macos_aarch64] Thread::current() called on detached thread
JDK-8262896: [macos_aarch64] Crash in jni_fast_GetLongField

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253795](https://bugs.openjdk.java.net/browse/JDK-8253795): Implementation of JEP 391: macOS/AArch64 Port ⚠️ Issue is not open.

### Reviewers
 * [Andrew Dinn](https://openjdk.java.net/census#adinn) (@adinn - **Reviewer**) ⚠️ Review applies to 774061e9afa6ffd86437b716f281116cfe2c46e7
 * [Bernhard Urban-Forster](https://openjdk.java.net/census#burban) (@lewurm - no project role) ⚠️ Review applies to 774061e9afa6ffd86437b716f281116cfe2c46e7

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/aarch64-port pull/14/head:pull/14` \
`$ git checkout pull/14`

Update a local copy of the PR: \
`$ git checkout pull/14` \
`$ git pull https://git.openjdk.java.net/aarch64-port pull/14/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14`

View PR using the GUI difftool: \
`$ git pr show -t 14`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/aarch64-port/pull/14.diff">https://git.openjdk.java.net/aarch64-port/pull/14.diff</a>

</details>

### CODE REVIEW

**Comment by lewurm** [comment]
I'm having troubles building it with Xcode 13.2:

```
=== Output from failing command(s) repeated here ===
* For target support_native_java.desktop_libsplashscreen_splashscreen_sys.o:
/Users/lewurm/private/aarch64-port/src/java.desktop/macosx/native/libsplashscreen/splashscreen_sys.m:274:39: error: 'NSAlphaFirstBitmapFormat' is deprecated: first deprecated in macOS 10.14 [-Werror,-Wdeprecated-declarations]
                        bitmapFormat: NSAlphaFirstBitmapFormat | NSAlphaNonpremultipliedBitmapFormat
                                      ^~~~~~~~~~~~~~~~~~~~~~~~
                                      NSBitmapFormatAlphaFirst
/Applications/Xcode13.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSBitmapImageRep.h:162:29: note: 'NSAlphaFirstBitmapFormat' has been expl
icitly marked deprecated here
static const NSBitmapFormat NSAlphaFirstBitmapFormat API_DEPRECATED_WITH_REPLACEMENT("NSBitmapFormatAlphaFirst", macos(10.5,10.14)) = NSBitmapFormatAlphaFirst;
                            ^
/Users/lewurm/private/aarch64-port/src/java.desktop/macosx/native/libsplashscreen/splashscreen_sys.m:274:66: error: 'NSAlphaNonpremultipliedBitmapFormat' is deprecated: first deprecated in macOS 10.14 [-Werror,-Wdeprecated-decl
arations]
                        bitmapFormat: NSAlphaFirstBitmapFormat | NSAlphaNonpremultipliedBitmapFormat
                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                 NSBitmapFormatAlphaNonpremultiplied
/Applications/Xcode13.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSBitmapImageRep.h:163:29: note: 'NSAlphaNonpremultipliedBitmapFormat' ha
s been explicitly marked deprecated here
static const NSBitmapFormat NSAlphaNonpremultipliedBitmapFormat API_DEPRECATED_WITH_REPLACEMENT("NSBitmapFormatAlphaNonpremultiplied", macos(10.0,10.14)) = NSBitmapFormatAlphaNonpremultiplied;
                            ^
/Users/lewurm/private/aarch64-port/src/java.desktop/macosx/native/libsplashscreen/splashscreen_sys.m:412:34: error: 'NSBorderlessWindowMask' is deprecated: first deprecated in macOS 10.12 [-Werror,-Wdeprecated-declarations]
   ... (rest of output omitted)

* All command lines available in /Users/lewurm/private/aarch64-port/build/macosx-aarch64-normal-server-release/make-support/failure-logs.
=== End of repeated output ===
```

Is this expected?

**Comment by VladimirKempik** [comment]
> I'm having troubles building it with Xcode 13.2:
> 
> ```
> === Output from failing command(s) repeated here ===
> * For target support_native_java.desktop_libsplashscreen_splashscreen_sys.o:
> /Users/lewurm/private/aarch64-port/src/java.desktop/macosx/native/libsplashscreen/splashscreen_sys.m:274:39: error: 'NSAlphaFirstBitmapFormat' is deprecated: first deprecated in macOS 10.14 [-Werror,-Wdeprecated-declarations]
>                         bitmapFormat: NSAlphaFirstBitmapFormat | NSAlphaNonpremultipliedBitmapFormat
>                                       ^~~~~~~~~~~~~~~~~~~~~~~~
>                                       NSBitmapFormatAlphaFirst
> /Applications/Xcode13.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSBitmapImageRep.h:162:29: note: 'NSAlphaFirstBitmapFormat' has been expl
> icitly marked deprecated here
> static const NSBitmapFormat NSAlphaFirstBitmapFormat API_DEPRECATED_WITH_REPLACEMENT("NSBitmapFormatAlphaFirst", macos(10.5,10.14)) = NSBitmapFormatAlphaFirst;
>                             ^
> /Users/lewurm/private/aarch64-port/src/java.desktop/macosx/native/libsplashscreen/splashscreen_sys.m:274:66: error: 'NSAlphaNonpremultipliedBitmapFormat' is deprecated: first deprecated in macOS 10.14 [-Werror,-Wdeprecated-decl
> arations]
>                         bitmapFormat: NSAlphaFirstBitmapFormat | NSAlphaNonpremultipliedBitmapFormat
>                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                                  NSBitmapFormatAlphaNonpremultiplied
> /Applications/Xcode13.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSBitmapImageRep.h:163:29: note: 'NSAlphaNonpremultipliedBitmapFormat' ha
> s been explicitly marked deprecated here
> static const NSBitmapFormat NSAlphaNonpremultipliedBitmapFormat API_DEPRECATED_WITH_REPLACEMENT("NSBitmapFormatAlphaNonpremultiplied", macos(10.0,10.14)) = NSBitmapFormatAlphaNonpremultiplied;
>                             ^
> /Users/lewurm/private/aarch64-port/src/java.desktop/macosx/native/libsplashscreen/splashscreen_sys.m:412:34: error: 'NSBorderlessWindowMask' is deprecated: first deprecated in macOS 10.12 [-Werror,-Wdeprecated-declarations]
>    ... (rest of output omitted)
> 
> * All command lines available in /Users/lewurm/private/aarch64-port/build/macosx-aarch64-normal-server-release/make-support/failure-logs.
> === End of repeated output ===
> ```
> 
> Is this expected?

Yes, this is expected, it's same in upstream IIRC, need to wait for a patch there first.
Just use --disable-warnings-as-errors configure argument

**Comment by lewurm** [comment]
Running fastdebug tier1 on macOS/AArch64 looks good:
```
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR
>> jtreg:test/hotspot/jtreg:tier1                     1239  1238     1     0 <<
>> jtreg:test/jdk:tier1                               1872  1866     6     0 <<
   jtreg:test/langtools:tier1                         3915  3915     0     0 
   jtreg:test/nashorn:tier1                              0     0     0     0
   jtreg:test/jaxp:tier1                                 0     0     0     0
==============================
TEST FAILURE
```

Those 6 failures in `jdk:tier` also happen on Linux/AArch64, so I'll ignore them. The hotspot failure happens on `test/hotspot/jtreg/runtime/ErrorHandling/TestOnError.java` with the following output:

```
TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: '^Test Succeeded' missing from stdout
```

Not sure what's going on.

Circeling back to the r18 issue mentioned here: https://github.com/openjdk/jdk11u-dev/pull/301#issuecomment-911998917
My understanding is that the current stable release of macOS (12.1 Monterey) should already be affected by this issue, as I haven't backported https://bugs.openjdk.java.net/browse/JDK-8274795 to jdk11 yet. Do you have some better reproducer other than running Intellij? Apparently none of the tier1 tests seem to trigger it. 

Edit: The `release` build of this branch actually runs Intellij just fine.

**Comment by VladimirKempik** [comment]
> Circeling back to the r18 issue mentioned here: [openjdk/jdk11u-dev#301 (comment)](https://github.com/openjdk/jdk11u-dev/pull/301#issuecomment-911998917) My understanding is that the current stable release of macOS (12.1 Monterey) should already be affected by this issue, as I haven't backported https://bugs.openjdk.java.net/browse/JDK-8274795 to jdk11 yet. Do you have some better reproducer other than running Intellij? Apparently none of the tier1 tests seem to trigger it.
> 
> Edit: The `release` build of this branch actually runs Intellij just fine.

that issue was gone after final version of r18 patch were included into jdk11u
in fact the issue was with c2 registers allocations and some #ifdef __APPLE__ not working as expected in ad files.

**Comment by ahmedmuhsin** [comment]
Here are my tier2 tests results for the release build on Monterey 12.0.1/ Xcode 13.1:
```
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/hotspot/jtreg:tier2                      192   192     0     0   
>> jtreg:test/jdk:tier2                               3389  3383     4     2 <<
   jtreg:test/langtools:tier2                           12    12     0     0   
   jtreg:test/nashorn:tier2                             36    36     0     0   
   jtreg:test/jaxp:tier2                               438   438     0     0   
==============================
TEST FAILURE
```

Fail
- java/net/NetworkInterface/UniqueMacAddressesTest.java: Tests that the MAC addresses returned by NetworkInterface.getNetworkInterfaces are unique for each adapter.
  - result: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: mac address uniqueness test failed
- java/net/Socket/LinkLocal.java: Connecting to a link-local IPv6 address should not causes a SocketException to be thrown.
  - result: Failed. Execution failed: `main' threw exception: java.net.SocketTimeoutException: Receive timed out
- java/net/Socket/UrgentDataTest.java: TCP Urgent data support
  - result: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Exception caught (UrgentDataTest.java:120)
- java/nio/channels/Selector/OutOfBand.java: OOB data causes a SocketChannel, with OOBINLINE disabled, to be selected
  - result: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Received more than expected

Error
- java/net/ipv6tests/UdpTest.java: IPv6 support for Windows XP and 2003 server
  - result: Error. Agent error: java.lang.Exception: Agent 26 timed out with a timeout of 480 seconds; check console log for any additional details
- java/nio/channels/DatagramChannel/MinSendBufferSize.java: Check that new SO_SNDBUF limit on macOS is adhered to
  - result: Error. test was interrupted! (timeout)



@lewurm  I am also getting the same `TestOnError` failure in hotspot:tier1 when I run the tests on the fastdebug build. However, I do not get the 6 langtools failures.  All tier1 tests pass on the release build though.

**Comment by VladimirKempik** [comment]
Thanks, these tier2 failures for network tests are common for macos_intel and macos_aarch64, they might requres special setup of network interfaces on the host

>TestOnError failure in hotspot:tier1 when I run the tests on the fastdebug build.

I'll check that, thanks.

**Review by adinn — APPROVED** [review]
Approved

**Comment by lewurm** [comment]
> @lewurm I am also getting the same `TestOnError` failure in hotspot:tier1 when I run the tests on the fastdebug build. However, I do not get the 6 langtools failures. All tier1 tests pass on the release build though.

Thanks for looking at it @ahmedmuhsin, probably an issue with my setup then.

> Edit: The release build of this branch actually runs Intellij just fine.

Running on that build for >48h now. Seems good 🙂 (it doesn't just sit in the background, but I'm actually using it).

> Is there an issue here that prevents 8274795 from being backported to 11? It's
> obviously a bug. Are you waiting for the MacOS port?

Yes, I was hoping the macOS port nicely crashes 😉  Here is the backport: https://github.com/openjdk/jdk11u-dev/pull/744

-------------------------------

@VladimirKempik not sure how you would like to proceed with this, do you want to merge this PR into `jdk11-macos` or do we just let it sit and bake here?  Both is fine I think.

**Comment by VladimirKempik** [comment]
@lewurm just proceed with https://github.com/openjdk/jdk11u-dev/pull/744 it's independent of this PR

**Comment by lewurm** [comment]
> @lewurm just proceed with [openjdk/jdk11u-dev#744](https://github.com/openjdk/jdk11u-dev/pull/744) it's independent of this PR

I meant _this_ PR: https://github.com/openjdk/aarch64-port/pull/14 🙂  I think there aren't any (strict) formal processes for the aarch64 project.

**Review by lewurm — APPROVED** [review]

**Comment by VladimirKempik** [comment]
About TestOnError test failure,  
this is a debug-only test and it really fails on macos-aarch64 fastdebug build. 
Easy to reproduce command line:

`./build/macosx-aarch64-normal-server-fastdebug/images/jdk/bin/java -XX:-TransmitErrorReport -XX:-CreateCoredumpOnCrash -XX:ErrorHandlerTest=12 -XX:OnError="echo Test" -version
`
results in 
`zsh: trace trap  ./build/macosx-aarch64-normal-server-fastdebug/images/jdk/bin/java`
and  in logs one can see:
`kernel	AMFI: Denying core dump for pid 69372 (java)`

This  happens due to the miss of this backport : https://github.com/openjdk/jdk/commit/c37eabe7

we have 3 options:
1) backport that rather bigpatch into jdk11
2) exclude this test on macos-aarch64
3) change the test from -XX:ErrorHandlerTest=12 to -XX:ErrorHandlerTest=14 which makes it crash like expected.

@theRealAph @adinn and other, what do you think about this one ?

**Comment by VladimirKempik** [comment]
So what ErrorHandlerTest=12 does is basically this:
 char * const dataPtr = NULL;
 *dataPtr = '\0';

and this code alone ( in a simple app) does behave differently on mac_intel and mac_arm ( both with ulimit -c unlimited and user writable /cores folder)

mac_intel does this:
Segmentation fault: 11 (core dumped)
the core is then present in /cores folder

mac_arm does this:
zsh: segmentation fault  ./testcrash
and printing this in dmesg:
[542308.736586]: AMFI: Denying core dump for pid 2283 (testcrash)testcrash[2283] Corpse allowed 1 of 5

so I believe the correct way is the way number 2
If no objections, I will update the PR in few days to ignore this test on mac_arm

**Comment by adinn** [comment]
@VladimirKempik I agree the best approach is just to exclude this on macos-aarch64.

**Comment by VladimirKempik** [comment]
@theRealAph Can I push this now into aarch64-port  repo?

**Comment by theRealAph** [comment]
> @theRealAph Can I push this now into aarch64-port repo?

Yes, thank you.

**Pull request closed without merging**
